name: GCP Deploy

on:
  push:
    branches: 
      - master
  pull_request:
    branches: [master]
      
jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v2
      - name: Deploy to GCP
        uses: fifsky/ssh-action@master
        with:
          command: |
            cd /var/www/url-shortener
            git pull --no-edit
            npm install
            pm2 restart 0
          host: ${{ secrets.HOST }}
          user: kavinvalli
          key: ${{ secrets.PRIVATE_KEY }}
